// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250919123204_Changed Enums and Added Seed Data")]
    partial class ChangedEnumsandAddedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ToolId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 346, DateTimeKind.Utc).AddTicks(30),
                            EndDate = new DateTime(2025, 9, 26, 12, 32, 4, 346, DateTimeKind.Utc).AddTicks(30),
                            MemberId = 1,
                            StartDate = new DateTime(2025, 9, 19, 12, 32, 4, 346, DateTimeKind.Utc).AddTicks(30),
                            Status = 1,
                            ToolId = 1,
                            UpdatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 346, DateTimeKind.Utc).AddTicks(30)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 346, DateTimeKind.Utc).AddTicks(30),
                            EndDate = new DateTime(2025, 9, 22, 12, 32, 4, 346, DateTimeKind.Utc).AddTicks(30),
                            MemberId = 2,
                            StartDate = new DateTime(2025, 9, 20, 12, 32, 4, 346, DateTimeKind.Utc).AddTicks(30),
                            Status = 0,
                            ToolId = 2,
                            UpdatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 346, DateTimeKind.Utc).AddTicks(30)
                        });
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CertificationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ToolId");

                    b.ToTable("Certifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CertificationDate = new DateTime(2023, 9, 19, 12, 32, 4, 345, DateTimeKind.Utc).AddTicks(9990),
                            CreatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 345, DateTimeKind.Utc).AddTicks(9990),
                            ExpirationDate = new DateTime(2026, 9, 19, 12, 32, 4, 345, DateTimeKind.Utc).AddTicks(9990),
                            MemberId = 1,
                            ToolId = 1,
                            Type = 0,
                            UpdatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 345, DateTimeKind.Utc).AddTicks(9990)
                        },
                        new
                        {
                            Id = 2,
                            CertificationDate = new DateTime(2024, 9, 19, 12, 32, 4, 345, DateTimeKind.Utc).AddTicks(9990),
                            CreatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 345, DateTimeKind.Utc).AddTicks(9990),
                            ExpirationDate = new DateTime(2026, 9, 19, 12, 32, 4, 345, DateTimeKind.Utc).AddTicks(9990),
                            MemberId = 2,
                            ToolId = 1,
                            Type = 0,
                            UpdatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 346, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CertificationDate = new DateTime(2025, 3, 19, 12, 32, 4, 346, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 346, DateTimeKind.Utc),
                            ExpirationDate = new DateTime(2026, 3, 19, 12, 32, 4, 346, DateTimeKind.Utc),
                            MemberId = 1,
                            ToolId = 1,
                            Type = 1,
                            UpdatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 346, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CertificationDate = new DateTime(2025, 6, 19, 12, 32, 4, 346, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 346, DateTimeKind.Utc),
                            ExpirationDate = new DateTime(2026, 6, 19, 12, 32, 4, 346, DateTimeKind.Utc),
                            MemberId = 1,
                            ToolId = 2,
                            Type = 2,
                            UpdatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 346, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MembershipDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Storgatan 1",
                            Email = "anna@example.com",
                            IsActive = true,
                            MembershipDate = new DateTime(2023, 9, 19, 12, 32, 4, 345, DateTimeKind.Utc).AddTicks(9940),
                            Name = "Anna Andersson",
                            PersonalNumber = "8501011234",
                            PhoneNumber = "0701234567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Lillgatan 5",
                            Email = "bjorn@example.com",
                            IsActive = true,
                            MembershipDate = new DateTime(2024, 9, 19, 12, 32, 4, 345, DateTimeKind.Utc).AddTicks(9950),
                            Name = "Björn Berg",
                            PersonalNumber = "9202025678",
                            PhoneNumber = "0709876543"
                        });
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Condition")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DemandsCertification")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Tools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Condition = 1,
                            CreatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 345, DateTimeKind.Utc).AddTicks(9970),
                            DemandsCertification = true,
                            Description = "En kraftfull borrmaskin",
                            IsAvailable = true,
                            Name = "Borrmaskin",
                            UpdatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 345, DateTimeKind.Utc).AddTicks(9970),
                            WorkshopId = 1
                        },
                        new
                        {
                            Id = 2,
                            Condition = 1,
                            CreatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 345, DateTimeKind.Utc).AddTicks(9980),
                            DemandsCertification = true,
                            Description = "MIG-svets för metall",
                            IsAvailable = true,
                            Name = "Svets",
                            UpdatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 345, DateTimeKind.Utc).AddTicks(9980),
                            WorkshopId = 2
                        });
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Workshops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 345, DateTimeKind.Utc).AddTicks(9830),
                            Description = "För träarbeten",
                            Name = "Snickeriverkstaden",
                            UpdatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 345, DateTimeKind.Utc).AddTicks(9830)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 345, DateTimeKind.Utc).AddTicks(9830),
                            Description = "För metallarbete och svetsning",
                            Name = "Metallverkstaden",
                            UpdatedDate = new DateTime(2025, 9, 19, 12, 32, 4, 345, DateTimeKind.Utc).AddTicks(9830)
                        });
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Booking", b =>
                {
                    b.HasOne("SUT24_TooliRent_V2_Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SUT24_TooliRent_V2_Domain.Entities.Tool", "Tool")
                        .WithMany("Bookings")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Certification", b =>
                {
                    b.HasOne("SUT24_TooliRent_V2_Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SUT24_TooliRent_V2_Domain.Entities.Tool", "Tool")
                        .WithMany("Certifications")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Tool", b =>
                {
                    b.HasOne("SUT24_TooliRent_V2_Domain.Entities.Workshop", "Workshop")
                        .WithMany("Tools")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Tool", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Certifications");
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Workshop", b =>
                {
                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
