// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CertificationTool", b =>
                {
                    b.Property<int>("CertificationsId")
                        .HasColumnType("int");

                    b.Property<int>("ToolsId")
                        .HasColumnType("int");

                    b.HasKey("CertificationsId", "ToolsId");

                    b.HasIndex("ToolsId");

                    b.ToTable("CertificationTool");
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3270),
                            EndDate = new DateTime(2025, 10, 6, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3270),
                            MemberId = 1,
                            StartDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3270),
                            Status = 1,
                            UpdatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3270)
                        });
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.BookingTool", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReturnStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingId", "ToolId");

                    b.HasIndex("ToolId");

                    b.ToTable("BookingTools");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            ToolId = 1,
                            CreatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3290),
                            ReturnStatus = 1,
                            UpdatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3290)
                        },
                        new
                        {
                            BookingId = 1,
                            ToolId = 2,
                            CreatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3290),
                            ReturnStatus = 1,
                            UpdatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3290)
                        });
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CertificationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int?>("ToolId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ToolId");

                    b.ToTable("Certifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CertificationDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3300),
                            CreatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3300),
                            ExpirationDate = new DateTime(2026, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3300),
                            MemberId = 1,
                            Type = "General",
                            UpdatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3300)
                        },
                        new
                        {
                            Id = 2,
                            CertificationDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3310),
                            CreatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3310),
                            ExpirationDate = new DateTime(2026, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3310),
                            MemberId = 2,
                            Type = "PowerTools",
                            UpdatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3310)
                        },
                        new
                        {
                            Id = 3,
                            CertificationDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3330),
                            CreatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3340),
                            ExpirationDate = new DateTime(2026, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3330),
                            MemberId = 1,
                            ToolId = 2,
                            Type = "WorkshopSpecific",
                            UpdatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3340)
                        });
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MembershipDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MembershipValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Storgatan 1",
                            Email = "anna@example.com",
                            IsActive = true,
                            MembershipDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3240),
                            MembershipValidUntil = new DateTime(2026, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3240),
                            Name = "Anna Andersson",
                            PersonalNumber = "19800101-1234",
                            PhoneNumber = "0701234567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Lillgatan 2",
                            Email = "bertil@example.com",
                            IsActive = true,
                            MembershipDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3250),
                            MembershipValidUntil = new DateTime(2026, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3250),
                            Name = "Bertil Bengtsson",
                            PersonalNumber = "19900202-5678",
                            PhoneNumber = "0709876543"
                        });
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DemandsCertification")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ToolCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToolCategoryId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Tools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Condition = "Good",
                            CreatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3220),
                            DemandsCertification = false,
                            Description = "Standard hammare",
                            IsAvailable = true,
                            Name = "Hammare",
                            ToolCategoryId = 1,
                            UpdatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3220),
                            WorkshopId = 1
                        },
                        new
                        {
                            Id = 2,
                            Condition = "Good",
                            CreatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3220),
                            DemandsCertification = true,
                            Description = "Elborrmaskin 500W",
                            IsAvailable = true,
                            Name = "Borrmaskin",
                            ToolCategoryId = 2,
                            UpdatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3220),
                            WorkshopId = 1
                        },
                        new
                        {
                            Id = 3,
                            Condition = "NeedsRepair",
                            CreatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3220),
                            DemandsCertification = true,
                            Description = "Industrisvets",
                            IsAvailable = false,
                            Name = "Svets",
                            ToolCategoryId = 3,
                            UpdatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3220),
                            WorkshopId = 2
                        });
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.ToolCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ToolCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3090),
                            Description = "Skruvmejslar, hammare, tänger",
                            Name = "Handverktyg",
                            UpdatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3090)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3090),
                            Description = "Borrmaskiner, cirkelsågar",
                            Name = "Elverktyg",
                            UpdatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3090)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3090),
                            Description = "Tyngre utrustning som CNC, svets",
                            Name = "Maskiner",
                            UpdatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3090)
                        });
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Workshops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3190),
                            Description = "För träarbete",
                            Name = "Träverkstad",
                            UpdatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3200)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3200),
                            Description = "För metallbearbetning",
                            Name = "Metallverkstad",
                            UpdatedDate = new DateTime(2025, 9, 29, 7, 21, 36, 91, DateTimeKind.Utc).AddTicks(3200)
                        });
                });

            modelBuilder.Entity("CertificationTool", b =>
                {
                    b.HasOne("SUT24_TooliRent_V2_Domain.Entities.Certification", null)
                        .WithMany()
                        .HasForeignKey("CertificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SUT24_TooliRent_V2_Domain.Entities.Tool", null)
                        .WithMany()
                        .HasForeignKey("ToolsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Booking", b =>
                {
                    b.HasOne("SUT24_TooliRent_V2_Domain.Entities.Member", "Member")
                        .WithMany("Bookings")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.BookingTool", b =>
                {
                    b.HasOne("SUT24_TooliRent_V2_Domain.Entities.Booking", "Booking")
                        .WithMany("BookingTools")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SUT24_TooliRent_V2_Domain.Entities.Tool", "Tool")
                        .WithMany("BookingTools")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Certification", b =>
                {
                    b.HasOne("SUT24_TooliRent_V2_Domain.Entities.Member", "Member")
                        .WithMany("Certifications")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SUT24_TooliRent_V2_Domain.Entities.Tool", "Tool")
                        .WithMany("SpecialCertifications")
                        .HasForeignKey("ToolId");

                    b.Navigation("Member");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Tool", b =>
                {
                    b.HasOne("SUT24_TooliRent_V2_Domain.Entities.ToolCategory", "ToolCategory")
                        .WithMany("Tools")
                        .HasForeignKey("ToolCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SUT24_TooliRent_V2_Domain.Entities.Workshop", "Workshop")
                        .WithMany("Tools")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ToolCategory");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Booking", b =>
                {
                    b.Navigation("BookingTools");
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Member", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Certifications");
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Tool", b =>
                {
                    b.Navigation("BookingTools");

                    b.Navigation("SpecialCertifications");
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.ToolCategory", b =>
                {
                    b.Navigation("Tools");
                });

            modelBuilder.Entity("SUT24_TooliRent_V2_Domain.Entities.Workshop", b =>
                {
                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
